"""baseline schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 17:13:35.115752
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'DISMISSED', name='flagstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.Enum('LOST', 'FOUND', name='reporttype'), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('distinctive_features', sa.Text(), nullable=True),
    sa.Column('private_details', sa.Text(), nullable=True),
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'POTENTIAL_MATCH', 'CONNECTED', 'RECOVERED', 'CLOSED', 'EXPIRED', 'DEACTIVATED', name='reportstatus'), nullable=False),
    sa.Column('ai_status', sa.Enum('PENDING', 'DONE', 'FAILED', name='aistatus'), nullable=False),
    sa.Column('ai_error', sa.String(length=255), nullable=True),
    sa.Column('text_embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_reports_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_reports_date_time'), ['date_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_reports_report_type'), ['report_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_reports_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('item_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('attribute_name', sa.String(length=50), nullable=False),
    sa.Column('attribute_value', sa.String(length=200), nullable=False),
    sa.Column('source', sa.Enum('USER', 'AI', name='attributesource'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['item_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_attributes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_attributes_report_id'), ['report_id'], unique=False)

    op.create_table('item_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['item_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_images_report_id'), ['report_id'], unique=False)

    op.create_table('match_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lost_report_id', sa.Integer(), nullable=False),
    sa.Column('found_report_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('POTENTIAL_MATCH', 'VERIFICATION_PENDING', 'AWAITING_FINDER_REVIEW', 'VERIFIED', 'REJECTED', 'DISMISSED', name='matchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['found_report_id'], ['item_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lost_report_id'], ['item_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lost_report_id', 'found_report_id')
    )
    with op.batch_alter_table('match_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_candidates_found_report_id'), ['found_report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_candidates_lost_report_id'), ['lost_report_id'], unique=False)

    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CONNECTED', 'RECOVERED', 'CLOSED', name='casestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match_candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_table('verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('advisory_score', sa.Float(), nullable=True),
    sa.Column('advisory_notes', sa.JSON(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match_candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verifications_match_id'), ['match_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_case_id'), ['case_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_case_id'))

    op.drop_table('messages')
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verifications_match_id'))

    op.drop_table('verifications')
    op.drop_table('cases')
    with op.batch_alter_table('match_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_candidates_lost_report_id'))
        batch_op.drop_index(batch_op.f('ix_match_candidates_found_report_id'))

    op.drop_table('match_candidates')
    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_images_report_id'))

    op.drop_table('item_images')
    with op.batch_alter_table('item_attributes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_attributes_report_id'))

    op.drop_table('item_attributes')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('item_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_item_reports_status'))
        batch_op.drop_index(batch_op.f('ix_item_reports_report_type'))
        batch_op.drop_index(batch_op.f('ix_item_reports_date_time'))
        batch_op.drop_index(batch_op.f('ix_item_reports_category'))

    op.drop_table('item_reports')
    op.drop_table('flags')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
