"""structured report location

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-03 17:14:08.734727
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('location_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('place_key', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_reports', schema=None) as batch_op:
        batch_op.drop_column('place_key')
        batch_op.drop_column('location_type')
        batch_op.drop_column('zone')

    # ### end Alembic commands ###
